on: 
    push:
        branches: ['**']
        tags-ignore: ['**']  # Ignore all tag pushes
    pull_request:

jobs:
 testmatrix:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
        run:
            shell: zsh -l {0}
    strategy:
        fail-fast: false
        matrix:
            cfg:
            - { os: macos-26        , desc: 'macOS Tahoe arm64' }
            - { os: macos-15-intel  , desc: 'macOS Sequoia x86_64' }
    name: ${{ matrix.cfg.desc }}
    steps: 
    - uses: actions/checkout@v6
    - run: |
        sudo mv xbrew.sh /usr/local/bin/xbrew
        sudo chmod +x /usr/local/bin/xbrew
        brew info doxygen
        xbrew reinstall doxygen d2267b9f2ad247bc9c8273eb755b39566a474a70
        xbrew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/d2267b9f2ad247bc9c8273eb755b39566a474a70/Formula/doxygen.rb
        xbrew reinstall doxygen 1.9.6
        brew pin doxygen
        brew info cmake
        xbrew reinstall --cask cmake 06eed90d6268ed8c26e23b0458a43f8d3317f66c
        xbrew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-cask/06eed90d6268ed8c26e23b0458a43f8d3317f66c/Casks/c/cmake.rb
        xbrew reinstall --cask cmake 3.31.6
        brew pin cmake
